# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3efa5089f412309f9a8a1a16a019c5b10097667514b1c322ea01a5fed219f4d67139fe57f7b60a09fcef0961d62abab461ba9c28e38861aa9888d22344047759

test:
  secret_key_base: 75c492ffd32abd22acee8b82d0d143d51ffd31efb5cb3ac3b5e2f5b7a7c49d32514389bfeca4e051c678944ad85ce83499af3d1dc99c7ca2c40aa5fba9526a0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
